### Obtener todas las tareas
GET http://192.168.20.25:8000/api/tareas/?last_doc_id=ozRxq6Rrdu6CfJA1kldF
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXZpZGVuY2lhMi1mZjNjOCIsImF1ZCI6ImV2aWRlbmNpYTItZmYzYzgiLCJhdXRoX3RpbWUiOjE3NzI3NDY1MDYsInVzZXJfaWQiOiJEcXFtQ21BRnYyVEtjN2hKQXh6Z3VwSHhJdDczIiwic3ViIjoiRHFxbUNtQUZ2MlRLYzdoSkF4emd1cEh4SXQ3MyIsImlhdCI6MTc3Mjc0NjUwNiwiZXhwIjoxNzcyNzUwMTA2LCJlbWFpbCI6InpldGExQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ6ZXRhMUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.naxizXC1V5o4kqiyklmGm_VKB25aG-8MrCPCh0ZjvjQAXycAPcVjdluIl7zEgxJgnK07dDX6gkqEi4rgwIrCAS_Izq5dsFnyLilRNhRda5BPcIkFGJdQYNJwzsDaQhhM8KyD9HbsAa4dQ83d7dQS3NzLAsLBOQSs03ZHGXCEp6vSd-a-IiSiW8aKxB41WUCeIshckwXRQOwC7WOFIqH_rJrPpLVSHUCofsksA0wU568OlVETcFl8-3FkOrQTLuRU_Me2hxRFHYzbg4RFkRVvmONM8bdQ1QQis0FomOkScUzh0ecSEjTf3F27r6OtmCOW8CeZZn-DrQfAnDPsimHuPw
### 1. Registrar un nuevo usuario (POST)
POST http://192.168.20.25:8000/api/auth/registro/
Content-Type: application/json

{
    "email": "andres@gmail.com",
    "password": "123456"
}


### 2. Iniciar sesión para conseguir el Token (POST)
POST http://192.168.20.25:8000/api/auth/login/
Content-Type: application/json

{
    "email": "andres@gmail.com",
    "password": "123456"
}

### 3. Crear una tarea USANDO EL TOKEN (POST)
POST http://192.168.20.25:8000/api/tareas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXZpZGVuY2lhMjIyLWY2M2ZmIiwiYXVkIjoiZXZpZGVuY2lhMjIyLWY2M2ZmIiwiYXV0aF90aW1lIjoxNzc0MTIyNDI1LCJ1c2VyX2lkIjoiaFJiSWxzbEEwQVVBb1ZCdjl0THhFU2ZmVkhXMiIsInN1YiI6ImhSYklsc2xBMEFVQW9WQnY5dEx4RVNmZlZIVzIiLCJpYXQiOjE3NzQxMjI0MjUsImV4cCI6MTc3NDEyNjAyNSwiZW1haWwiOiJhbmRyZXNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFuZHJlc0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Pi3A_a8ovq4ASvhS4c4opmP66FnyFEwuwFcFNDyBHJmElkPXrR1pUbppCJZU_2sHvZrandpuhCpXLa9C6xhAZHWFD7bjrSkP-yXHyEEMTMcci_7xsU5HtWDMhEkB5bE-I6L1qCMlFa7KrVzk5SP_2F-f2484cXImbPlXwjFzus1G6UFmahYNAwCMKOwyAV7I8sefK0C0ukLFMIAHEuUkvNNL88LP3yL-zkOuySaN24OLbIYFf7apJjLabvjKUvq4paeaqZAr1vgLxfrf_nqGwwoy6PbXbp6zwB43CE6d-RPR-2jVjvObdL157XRK0l5En9DXW50ES-d3cRa7wREpDA

{
    "titulo": "Tarea primera",
    "descripcion": "prueba"
}

# ### 4. Eliminar una tarea (DELETE)
# POST http://192.168.20.25:8000/api/tareas/
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXZpZGVuY2lhMi1mZjNjOCIsImF1ZCI6ImV2aWRlbmNpYTItZmYzYzgiLCJhdXRoX3RpbWUiOjE3NzI1NzEyNjIsInVzZXJfaWQiOiJmMEI0U3NwZHRFT1NCY0RCRHJwSWpwT29OUEUzIiwic3ViIjoiZjBCNFNzcGR0RU9TQmNEQkRycElqcE9vTlBFMyIsImlhdCI6MTc3MjU3MTI2MiwiZXhwIjoxNzcyNTc0ODYyLCJlbWFpbCI6InpldGEyQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ6ZXRhMkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.rH3sGJ4r264_LhHOm4BWEtCnNjbKIONZe7IzOuRPVLuz6yOc5GmIwxCwL3OkNWy7-UU72sonCXgnzTdetdRf0tRglZCJ5Eje2sRBQp0PPpy8AQu_0rV66SMcD4pogZRuIZCEbrARE3BkRhxFjr9RjRArxzt9YR6YGECWIfzBQfLf6_iyXmL5ZTKS5EvlK1p0lmGEz3ff_emX5hiKNQOF0bUYd_G7NjX_PP53FrB8FdyYy-jB6GEB82jkV0t5Wrxchc9puQni5Hz4nd0NOIKRv5IdKSI4tq8rtO0gI_a8emIEathA-YL_mDP973_Rbq148d340dJpLIzV_IlMw2sPWg

# {
#     "titulo": "leelo porfa2",
# }

### Eliminar una tarea


DELETE http://192.168.20.25:8000/api/tareas/UoKjQJFQ2zaZCn2WzDGU/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXZpZGVuY2lhMjIyLWY2M2ZmIiwiYXVkIjoiZXZpZGVuY2lhMjIyLWY2M2ZmIiwiYXV0aF90aW1lIjoxNzc0MTIyNDI1LCJ1c2VyX2lkIjoiaFJiSWxzbEEwQVVBb1ZCdjl0THhFU2ZmVkhXMiIsInN1YiI6ImhSYklsc2xBMEFVQW9WQnY5dEx4RVNmZlZIVzIiLCJpYXQiOjE3NzQxMjI0MjUsImV4cCI6MTc3NDEyNjAyNSwiZW1haWwiOiJhbmRyZXNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFuZHJlc0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Pi3A_a8ovq4ASvhS4c4opmP66FnyFEwuwFcFNDyBHJmElkPXrR1pUbppCJZU_2sHvZrandpuhCpXLa9C6xhAZHWFD7bjrSkP-yXHyEEMTMcci_7xsU5HtWDMhEkB5bE-I6L1qCMlFa7KrVzk5SP_2F-f2484cXImbPlXwjFzus1G6UFmahYNAwCMKOwyAV7I8sefK0C0ukLFMIAHEuUkvNNL88LP3yL-zkOuySaN24OLbIYFf7apJjLabvjKUvq4paeaqZAr1vgLxfrf_nqGwwoy6PbXbp6zwB43CE6d-RPR-2jVjvObdL157XRK0l5En9DXW50ES-d3cRa7wREpDA



###subir imagen de perfil al usuario

POST http://192.168.20.25:8000/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZXZpZGVuY2lhMjIyLWY2M2ZmIiwiYXVkIjoiZXZpZGVuY2lhMjIyLWY2M2ZmIiwiYXV0aF90aW1lIjoxNzc0MTIyNDI1LCJ1c2VyX2lkIjoiaFJiSWxzbEEwQVVBb1ZCdjl0THhFU2ZmVkhXMiIsInN1YiI6ImhSYklsc2xBMEFVQW9WQnY5dEx4RVNmZlZIVzIiLCJpYXQiOjE3NzQxMjI0MjUsImV4cCI6MTc3NDEyNjAyNSwiZW1haWwiOiJhbmRyZXNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImFuZHJlc0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Pi3A_a8ovq4ASvhS4c4opmP66FnyFEwuwFcFNDyBHJmElkPXrR1pUbppCJZU_2sHvZrandpuhCpXLa9C6xhAZHWFD7bjrSkP-yXHyEEMTMcci_7xsU5HtWDMhEkB5bE-I6L1qCMlFa7KrVzk5SP_2F-f2484cXImbPlXwjFzus1G6UFmahYNAwCMKOwyAV7I8sefK0C0ukLFMIAHEuUkvNNL88LP3yL-zkOuySaN24OLbIYFf7apJjLabvjKUvq4paeaqZAr1vgLxfrf_nqGwwoy6PbXbp6zwB43CE6d-RPR-2jVjvObdL157XRK0l5En9DXW50ES-d3cRa7wREpDA
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpg"
Content-Type: image/jpeg

< C:\Users\andre\Downloads\evidencia2\avatar.jpg
--MiBoundary--